# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module
try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    import datetime
    sys.path.insert(0, os.path.abspath('..'))
    from conf_common import *  # noqa: F403,F401

current_year = datetime.datetime.now().year

# General information about the project.
project = u'ESP 测试工具'
copyright = u'2024 - {} 乐鑫信息科技（上海）股份有限公司'.format(current_year)
pdf_title = u'ESP 测试工具使用指南'
# Final PDF filename will contains target and version
pdf_file_prefix = u'esp-test-tools'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'zh_CN'

# Table, figure, and section numbering configurations
numfig_format = {
    'figure': '图 %s',
    'table': '表 %s',
}

# ----------------- Chinese-specific LaTeX configurations -----------------

cn_footer_toc_config = r'''
% ToC
\addto\captionsenglish{\renewcommand{\contentsname}{目录}}
'''

latex_elements['preamble'] = preamble + cn_footer_toc_config + preamble_extra
