# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module
try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    import datetime
    sys.path.insert(0, os.path.abspath('..'))
    from conf_common import *  # noqa: F403,F401

current_year = datetime.datetime.now().year

# General information about the project.
project = u'ESP 测试工具'
copyright = u'2024 - {} 乐鑫信息科技（上海）股份有限公司'.format(current_year)
pdf_title = u'ESP 测试工具使用指南'
# Final PDF filename will contains target and version
pdf_file_prefix = u'esp-test-tools'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'zh_CN'

doc_id = {'esp8266': '8101', 'esp32': '8123', 'esp32c2': '8125', 'esp32c3': '8127', 'esp32c6': '8129', 'esp32s2': '8131', 'esp32s3': '8133', 'esp32h2': '8135', 'esp32c5': '', 'esp32c61': ''}

# ----------------- Chinese-specific LaTeX configurations -----------------

cn_footer_toc_config = r'''
% Header and footer
\makeatletter
  \fancypagestyle{normal}{
    \fancyhf{}
    \fancyhead[L]{\nouppercase{\leftmark}}
    \fancyfoot[C]{\py@HeaderFamily\thepage \\ \href{https://www.espressif.com/zh-hans/company/documents/documentation_feedback?docId=\DocId&sections=&version=}{提交文档反馈}}
    \fancyfoot[L]{乐鑫信息科技}
    \fancyfoot[R]{{\idfTarget}{\@title}}
    \renewcommand{\headrulewidth}{0.4pt}
    \renewcommand{\footrulewidth}{0.4pt}
  }
\makeatother

\renewcommand{\headrulewidth}{0.5pt}
\renewcommand{\footrulewidth}{0.5pt}

% ToC
\addto\captionsenglish{\renewcommand{\contentsname}{目录}}
'''

latex_elements['preamble'] = preamble + cn_footer_toc_config + preamble_extra

html_js_files = ['js/chatbot_widget_cn.js']
